* Ob-arq

Org babel extension to perform sparql queries based on org babel source
blocks.

** Getting Started

*** Prerequisites

 - apache arq

Please refer to [[https://www.docker.com/products/docker-desktop][this page]] for more information on installing ~arq~.

*** Installation

Recommended install via [[https://github.com/jwiegley/use-package][use-package]] and [[https://github.com/quelpa/quelpa][quelpa]].

   #+begin_src emacs-lisp
(use-package ob-arq
  :ensure-system-package arq
  :ensure t
  :defer t
  :quelpa ((ob-arq :fetcher github :repo "ifitzpat/ob-arq") :upgrade t)
  :config
  (add-to-list 'org-babel-load-languages '(arq . t))
  (org-babel-do-load-languages 'org-babel-load-languages org-babel-load-languages)
)
   #+end_src


** Usage

Calling ~C-c C-c~ on arq source blocks calls ~arq query~
on that block. Use the ~:source~ header argument to specify which org babel source block
contains the rdf data to be queried.

: #+name: graphdata
: #+begin_src ttl
: @prefix example: <http://example.org/>.
:
: example:this a example:graph.
:
: #+end_src

: #+begin_src arq :source graphdata
: SELECT ?s
: WHERE { ?s ?p ?o. }
: #+end_src


** Roadmap


** Contributing

Contributions are what make the open source community such an amazing place to be learn, inspire, and create. Any contributions you make are extremely appreciated.

 1. Fork the Project
 2. Create your Feature Branch (git checkout -b feature/AmazingFeature)
 3. Commit your Changes (git commit -m 'Add some AmazingFeature')
 4. Push to the Branch (git push origin feature/AmazingFeature)
 5. Open a Pull Request


** License

Distributed under the GPLv3. See LICENSE for more information.

** Contact

Dr. Ian FitzPatrick - @ifitzpat - ian@ianfitzpatrick.eu

Project Link: https://github.com/fitzpat/ob-arq

** Acknowledgements


 - [[https://github.com/roshanlam/ReadMeTemplate][README template]]
